Repository digitalcampusframework/dcf, pull requests merged in 2019-11, with the labels that each got.

#309 Update aria-hidden states to handle nav toggle group correctly
  assets/dist/js/app/common/dcf-modal.min.js
  assets/dist/js/app/common/dcf-modal.min.js.map
  assets/dist/js/app/postBabel/common/dcf-modal.js
  assets/dist/js/app/preBabel/common/dcf-modal.js
  assets/src/js/app/common/dcf-modal.js
  example/includes/global/nav-toggle-group.html
  example/js/bundled/bundle.js
  example/js/bundled/bundle.js.map
  package-lock.json
  package.json
Labels: 1.0, enhancement, npm security fix

#308 Update bare list styles for local nav and app controls
  core/dist/scss/components/_components.nav-menu.scss
  core/src/scss/components/_components.nav-menu.scss
  theme/build/css/main.css
  theme/build/css/main.css.map
  theme/css/main.min.css
  theme/css/main.min.css.map
  theme/includes/global/nav-menu-1.html
  theme/includes/global/nav-menu-child-1.html
  theme/includes/global/nav-menu-child-2.html
  theme/index.shtml
Labels: 2.0

#311 Adjust nav toggle group button widths and flex [2.0]
  theme/build/css/main.css
  theme/build/css/main.css.map
  theme/build/scss/components/_components.nav-toggle.scss
  theme/css/main.min.css
  theme/css/main.min.css.map
  theme/includes/global/nav-toggle-group.html
  theme/scss/components/_components.nav-toggle.scss
Labels: 2.0

#310 Adjust nav toggle group button widths and flex [1.0]
  example/css/all.min.css
  example/css/all.min.css.map
  example/includes/global/nav-toggle-group.html
  example/scss/components/_components.nav-toggle.scss
Labels: 1.0

#314 Update nav toggle group markup, CSS
  theme/build/css/main.css.map
  theme/css/main.min.css
  theme/css/main.min.css.map
  theme/includes/global/nav-toggle-group.html
Labels: 2.0

#315 Update form help (instructions) for better a11y
  core/dist/scss/components/_components.forms.scss
  core/src/scss/components/_components.forms.scss
  theme/build/css/main.css
  theme/build/css/main.css.map
  theme/build/scss/variables/_variables.forms.scss
  theme/css/main.min.css
  theme/css/main.min.css.map
  theme/index.shtml
  theme/scss/variables/_variables.forms.scss
Labels: 2.0

#316 Move lazy-load, state CSS from "javascript" to "utilities"
  core/dist/scss/javascript/_javascript.lazy-load.scss
  core/dist/scss/utilities/_utilities.states.scss
  core/src/scss/javascript/_javascript.lazy-load.scss
  core/src/scss/utilities/_utilities.states.scss
  theme/build/css/main.css
  theme/build/css/main.css.map
  theme/build/scss/main.scss
  theme/css/main.min.css
  theme/css/main.min.css.map
  theme/index.shtml
  theme/scss/main.scss
Labels: 2.0, documentation

#317 Update variables: abbreviations, forms, math and comments
  core/dist/scss/components/_components.forms.scss
  core/dist/scss/elements/_elements.abbreviations.scss
  core/src/scss/components/_components.forms.scss
  core/src/scss/elements/_elements.abbreviations.scss
  theme/build/css/main.css
  theme/build/css/main.css.map
  theme/build/scss/variables/_variables.abbreviations.scss
  theme/build/scss/variables/_variables.backgrounds.scss
  theme/build/scss/variables/_variables.badges.scss
  theme/build/scss/variables/_variables.body.scss
  theme/build/scss/variables/_variables.breakpoints.scss
  theme/build/scss/variables/_variables.buttons.scss
  theme/build/scss/variables/_variables.forms-checkboxes-radios.scss
  theme/build/scss/variables/_variables.input-groups.scss
  theme/build/scss/variables/_variables.paragraphs.scss
  theme/build/scss/variables/_variables.sizing.scss
  theme/build/scss/variables/_variables.sup-sub.scss
  theme/build/scss/variables/_variables.tables.scss
  theme/build/scss/variables/_variables.transitions.scss
  theme/css/main.min.css
  theme/css/main.min.css.map
  theme/index.shtml
  theme/scss/variables/_variables.abbreviations.scss
  theme/scss/variables/_variables.backgrounds.scss
  theme/scss/variables/_variables.badges.scss
  theme/scss/variables/_variables.body.scss
  theme/scss/variables/_variables.breakpoints.scss
  theme/scss/variables/_variables.buttons.scss
  theme/scss/variables/_variables.forms-checkboxes-radios.scss
  theme/scss/variables/_variables.input-groups.scss
  theme/scss/variables/_variables.paragraphs.scss
  theme/scss/variables/_variables.sizing.scss
  theme/scss/variables/_variables.sup-sub.scss
  theme/scss/variables/_variables.tables.scss
  theme/scss/variables/_variables.transitions.scss
Labels: 2.0

#318 Add caption styles to tables components
  core/dist/scss/components/_components.tables.scss
  core/src/scss/components/_components.tables.scss
Labels: 2.0
