Repository digitalcampusframework/dcf, pull requests merged in 2023-10, with the labels that each got.

#510 Popup classes consistency
  js/dcf-popup.js
Labels: bug

#511 Add position-agnostic and dedicated centered grid columns
  scss/objects/_objects.grids.scss
Labels: enhancement, 3.0

#514 Add comments to aid searching for classes with percentages in their name
  scss/utilities/_utilities.opacity.scss
  scss/utilities/_utilities.position.scss
Labels: enhancement, documentation, 3.0
