Repository digitalcampusframework/dcf, pull requests merged in 2023-05, with the labels that each got.

#480 Add progress spinner component
  scss/components/_components.progress.scss
Labels: enhancement, 3.0

#477 Make all elements inside collapsed contents not focusable
  js/dcf-button-toggle.js
Labels: bug

#478 Toggle Keys Reference Bug
  js/dcf-button-toggle.js
  js/dcf-figcaption-toggle.js
Labels: bug

#479 Collapsible Fieldsets
  js/dcf-collapsible-fieldset.js
  scss/generic/_generic.reduced-motion.scss
  scss/mixins/_mixins.border-radius.scss
  scss/mixins/_mixins.height-width.scss
  scss/utilities/_utilities.border-radius.scss
  scss/utilities/_utilities.height-width.scss
Labels: enhancement

#484 Update popups (arrows and content)
  js/dcf-popup.js
  scss/components/_components.popups.scss
  scss/variables/_variables.tmp-defaults.scss
Labels: 3.0

#486 Update default variables for popups
  scss/variables/_variables.tmp-defaults.scss
Labels: bug, 3.0

#487 Fix margin variable name for popups
  scss/components/_components.popups.scss
Labels: bug, 3.0

#489 Fix position of default popup point (arrow)
  scss/components/_components.popups.scss
Labels: bug, 3.0

#490 Bug Fix for aria label being set without value
  js/dcf-button-toggle.js
Labels: bug

#491 Animation block
  js/dcf-collapsible-fieldset.js
  scss/utilities/_utilities.animation.scss
Labels: bug, enhancement
