Repository digitalcampusframework/dcf, pull requests merged in 2023-06, with the labels that each got.

#492 Tabs update
  js/dcf-tabs.js
  js/dcf-utility.js
Labels: enhancement

#493 Remove nav-menu-child pseudo content
  scss/components/_components.nav-menu.scss
Labels: 3.0

#495 Tabs scroll
  js/dcf-tabs.js
  scss/components/_components.tabs.scss
Labels: enhancement

#494 Remove duplicate nav menu styles from app.scss
  scss/components/_components.app.scss
Labels: duplicate, 3.0

#496 Fix links with base tag from opening in wrong location
  js/dcf-tabs.js
  scss/components/_components.tabs.scss
Labels: bug
